language: node_js
node_js:
- 7.7.1
notifications:
  email: false
  slack:
    secure: B/q5TMvRpesX/RqfvRhUYSVYnEkMRmUvH+oT/CUSni72KjIZ1vcN9FtLUZ65W1Vd1TQ4o9tLXknmMqSGcjvKOXr4Eam0Le6MZPifg7Qx15+KY0AylWajPQKO5/QRB5v7JY+0IXAIEm2ZGYIsnB+Psk8dNUrCrPTgzITU5U9RI4+7S0SQ4njHq0FTf2SRwOzKmiErXlspfytvNw/WHTPY1a62jVVs5eadtSzRedNxrqwviPpCr348MX3VBGHjaEY03dVK2ykNnwWmLaAYwoaFW7K8DM6IR2FJ8FhZRasJEgB4ZJhcl74244gbquz3vhFODPuj1erQPHvCRLD8bVBiRligmy5cIjXfAE86KA8JeiJ3++DOepknLt7gEfeoYX/0N5zAindkbRb4zhFh2B7mCInshg9XQtpmunypNp/H8JMEAinhtcaGrD3lN43zzGX2PuW7SAVsd6E8llnCGlBP40lWGFCMHjWihcLBHsIlAxdb3jdiW3CgEGAjXq39UybQhIFxTWEhepg5iRAGQCNiA32LPHLi26E8zxUG8yeoPDnlfEy2mUA5qY74VUO4vdkAw0FOMu0P4+9DJ6aHcwGjrRS6WcKwXcxRkcIqmem2ZOQJr2Z6zp7c3qtCq5/LT7eKouaBXG34gCbY84ZSo7yA7sijVOM5EKr0kUBO5N9tOBA=
